services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: intervention
      POSTGRES_PASSWORD: intervention
      POSTGRES_DB: intervention
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z

volumes:
  postgres_data: